INSERT INTO CATEGORY (ID, NAME) VALUES (1, 'FOOD');
INSERT INTO CATEGORY (ID, NAME) VALUES (2, 'BOOK');
INSERT INTO CATEGORY (ID, NAME) VALUES (3, 'DVD');

INSERT INTO ITEM (NAME, CATEGORY_ID) VALUES ('Apple', 1);
INSERT INTO ITEM (NAME, CATEGORY_ID) VALUES ('Orange', 1);
INSERT INTO ITEM (NAME, CATEGORY_ID) VALUES ('Grape', 1);

INSERT INTO ITEM (NAME, CATEGORY_ID) VALUES ('Java In Action', 2);
INSERT INTO ITEM (NAME, CATEGORY_ID) VALUES ('ES2015 In Action', 2);

INSERT INTO ITEM (NAME, CATEGORY_ID) VALUES ('Titanic', 3);
INSERT INTO ITEM (NAME, CATEGORY_ID) VALUES ('Roman holiday', 3);
INSERT INTO ITEM (NAME, CATEGORY_ID) VALUES ('Matrix', 3);
INSERT INTO ITEM (NAME, CATEGORY_ID) VALUES ('STAR WARS', 3);
