CREATE TABLE IF NOT EXISTS CATEGORY (
    ID INT(100) PRIMARY KEY,
    NAME VARCHAR(20)
);

CREATE TABLE ITEM (
    ID INT(10000) DEFAULT 1 NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    PRICE INT(100000) NOT NULL,
    UNIT INT(100) NOT NULL,
    DESCRIPTION VARCHAR(200) NOT NULL,
    PICT CLOB,
    CATEGORY_ID INT(100),
    VERSIONNO BIGINT NOT NULL,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);
