CREATE TABLE IF NOT EXISTS CATEGORY (
    ID INT(100) PRIMARY KEY,
    NAME VARCHAR(20)
);

CREATE TABLE ITEM (
    ID INT(10000) DEFAULT 1 NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100),
    CATEGORY_ID INT(100),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);
