INSERT INTO ADDR (ZIPCODE, LOCATION, RECEIVERNAME) VALUES ('123-4567', 'Tokyo-Fuchu', 'SCOTT');
INSERT INTO ORDEREDITEM (ITEM_ID, ITEM_UNIT) VALUES (1, 5);
INSERT INTO ORDERHIST (SENDERNAME, ORDEREDITEM_ID, ADDR_ID) VALUES ('TIGER', 1, 1);
