 CREATE TABLE IF NOT EXISTS ADDR (
   ID INT(10000) DEFAULT 1 NOT NULL AUTO_INCREMENT,
   ZIPCODE VARCHAR(10) NOT NULL,
   LOCATION VARCHAR(50) NOT NULL,
   RECEIVERNAME VARCHAR(20) NOT NULL
 );

 CREATE TABLE IF NOT EXISTS ORDEREDITEM (
   ID INT(10000) DEFAULT 1 NOT NULL AUTO_INCREMENT,
   ITEM_ID INT(100) NOT NULL,
   ITEM_UNIT INT(100) NOT NULL
 );

 -- TODO I might add 'timestamp' to ORDEREDITEM table.

 CREATE TABLE IF NOT EXISTS ORDERHIST (
   ID INT(10000) PRIMARY KEY,
   SENDERNAME VARCHAR(20) NOT NULL,
   ORDEREDITEM_ID INT(10000) NOT NULL,
   ADDR_ID INT(10000) NOT NULL,
   FOREIGN KEY (ORDEREDITEM_ID) REFERENCES ORDEREDITEM(ID),
   FOREIGN KEY (ADDR_ID) REFERENCES ADDR(ID)
 );

-- TODO I may fix DDL to record bought multi items.
