 CREATE TABLE IF NOT EXISTS ADDR (
   ID BIGINT PRIMARY KEY NOT NULL,
   ZIPCODE VARCHAR(10) NOT NULL,
   LOCATION VARCHAR(50) NOT NULL,
   RECEIVERNAME VARCHAR(20) NOT NULL
 );

 CREATE TABLE IF NOT EXISTS ORDEREDITEM (
   ID BIGINT PRIMARY KEY NOT NULL,
   ITEM_ID INT(100) NOT NULL,
   ITEM_UNIT INT(100) NOT NULL
 );

 -- TODO: I might add 'timestamp' to ORDEREDITEM table.

 CREATE TABLE IF NOT EXISTS ORDERHIST (
   ID BIGINT PRIMARY KEY NOT NULL,
   SENDERNAME VARCHAR(20) NOT NULL,
   ORDEREDITEM_ID BIGINT NOT NULL,
   ADDR_ID BIGINT NOT NULL,
   FOREIGN KEY (ORDEREDITEM_ID) REFERENCES ORDEREDITEM(ID),
   FOREIGN KEY (ADDR_ID) REFERENCES ADDR(ID)
 );

-- TODO: I may fix DDL to record bought multi items.

-- Note: To store data likes timestamp as primary key, so I defined primary key using BIGINT.
